### ISSUE TITLE
Problem With Building The Project

### ISSUE THREAD

**Issue by Yanksi** [alecjacobson/computer-graphics-ray-casting#11]
I had just finished the code of my A2, however, when I was trying to make the executable. An error occurred when building the main function while I have no idea how to fix this problem. Here is the screenshot of the error message.

![alt text](https://preview.ibb.co/eJDSgp/1537921124_1.png "Screen shot")
>alexander@AlexanderLeeLight:/mnt/c/18fall/csc418/A2/computer-graphics-ray-casting-master/build$ make
>Scanning dependencies of target raycasting
>[ 11%] Building CXX object CMakeFiles/raycasting.dir/src/first_hit.cpp.o
>[ 22%] Building CXX object CMakeFiles/raycasting.dir/src/Plane.cpp.o
>[ 33%] Building CXX object CMakeFiles/raycasting.dir/src/Sphere.cpp.o
>[ 44%] Building CXX object CMakeFiles/raycasting.dir/src/Triangle.cpp.o
>[ 55%] Building CXX object CMakeFiles/raycasting.dir/src/TriangleSoup.cpp.o
>[ 66%] Building CXX object CMakeFiles/raycasting.dir/src/viewing_ray.cpp.o
>[ 77%] Building CXX object CMakeFiles/raycasting.dir/src/write_ppm.cpp.o
>[ 88%] Building CXX object CMakeFiles/raycasting.dir/main.cpp.o
In file included from /mnt/c/18fall/csc418/A2/computer-graphics-ray-casting-master/main.cpp:6:0:
/mnt/c/18fall/csc418/A2/computer-graphics-ray-casting-master/include/read_json.h: In lambda function:
/mnt/c/18fall/csc418/A2/computer-graphics-ray-casting-master/include/read_json.h:94:22: error: converting to ‘std::tuple<Eigen::Matrix<double, 3, 1, 0, 3, 1>, Eigen::Matrix<double, 3, 1, 0, 3, 1>, Eigen::Matrix<double, 3, 1, 0, 3, 1> >’ from initializer list would use explicit constructor ‘constexpr std::tuple< <template-parameter-1-1> >::tuple(_UElements&& ...) [with _UElements = {Eigen::Matrix<double, 3, 1, 0, 3, 1>, Eigen::Matrix<double, 3, 1, 0, 3, 1>, Eigen::Matrix<double, 3, 1, 0, 3, 1>}; <template-parameter-2-2> = void; _Elements = {Eigen::Matrix<double, 3, 1, 0, 3, 1>, Eigen::Matrix<double, 3, 1, 0, 3, 1>, Eigen::Matrix<double, 3, 1, 0, 3, 1>}]’
         tri->corners = {
                      ^
/mnt/c/18fall/csc418/A2/computer-graphics-ray-casting-master/include/read_json.h:121:24: error: converting to ‘std::tuple<Eigen::Matrix<double, 3, 1, 0, 3, 1>, Eigen::Matrix<double, 3, 1, 0, 3, 1>, Eigen::Matrix<double, 3, 1, 0, 3, 1> >’ from initializer list would use explicit constructor ‘constexpr std::tuple< <template-parameter-1-1> >::tuple(_UElements&& ...) [with _UElements = {Eigen::Matrix<double, 3, 1, 0, 3, 1>, Eigen::Matrix<double, 3, 1, 0, 3, 1>, Eigen::Matrix<double, 3, 1, 0, 3, 1>}; <template-parameter-2-2> = void; _Elements = {Eigen::Matrix<double, 3, 1, 0, 3, 1>, Eigen::Matrix<double, 3, 1, 0, 3, 1>, Eigen::Matrix<double, 3, 1, 0, 3, 1>}]’
           tri->corners = {
                        ^
CMakeFiles/raycasting.dir/build.make:230: recipe for target 'CMakeFiles/raycasting.dir/main.cpp.o' failed
make[2]: *** [CMakeFiles/raycasting.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/raycasting.dir/all' failed
make[1]: *** [CMakeFiles/raycasting.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by alecjacobson** [comment]
this is fixed in 71cf44378e3f081b5534c75a0ae089fa9cb2c080

`git pull` to update to this version.
