### ISSUE TITLE
make command not executing out of the box due to json.hpp

### ISSUE THREAD

**Issue by Desmeister** [alecjacobson/computer-graphics-ray-casting#15]
After running "make" from the build folder after doing cmake, I'm getting a large number of issues from the Javascript files. Can anyone advise? I'm working on the ECF machines, and I'm thinking it might be a compiler issue.

Here's the results of cmake in the build folder:
-- The C compiler identification is GNU 4.4.7                                 
-- The CXX compiler identification is GNU 4.4.7                               
-- Check for working C compiler: /usr/bin/cc                                  
-- Check for working C compiler: /usr/bin/cc -- works                         
-- Detecting C compiler ABI info                                              
-- Detecting C compiler ABI info - done                                       
-- Check for working CXX compiler: /usr/bin/c++                               
-- Check for working CXX compiler: /usr/bin/c++ -- works                      
-- Detecting CXX compiler ABI info                                            
-- Detecting CXX compiler ABI info - done                                     
-- Performing Test COMPILER_SUPPORTS_CXX11                                    
-- Performing Test COMPILER_SUPPORTS_CXX11 - Failed                           
-- Performing Test COMPILER_SUPPORTS_CXX0X                                    
-- Performing Test COMPILER_SUPPORTS_CXX0X - Success                          
-- Configuring done                                                           
-- Generating done                                                            
-- Build files have been written to: /u/c/sissonde/computer-graphics-ray-casting/build

And here's make:
Scanning dependencies of target raycasting                                            
[ 12%] Building CXX object CMakeFiles/raycasting.dir/src/write_ppm.cpp.o                                      
[ 25%] Building CXX object CMakeFiles/raycasting.dir/src/Plane.cpp.o                                          
[ 37%] Building CXX object CMakeFiles/raycasting.dir/src/Sphere.cpp.o                                         
[ 50%] Building CXX object CMakeFiles/raycasting.dir/src/TriangleSoup.cpp.o                                   
[ 62%] Building CXX object CMakeFiles/raycasting.dir/src/viewing_ray.cpp.o                                    
[ 75%] Building CXX object CMakeFiles/raycasting.dir/src/first_hit.cpp.o                                      
[ 87%] Building CXX object CMakeFiles/raycasting.dir/src/Triangle.cpp.o                                       
[100%] Building CXX object CMakeFiles/raycasting.dir/main.cpp.o                                               
In file included from /u/c/sissonde/computer-graphics-ray-casting/include/read_json.h:24,                     
                 from /u/c/sissonde/computer-graphics-ray-casting/main.cpp:6:                                 
/u/c/sissonde/computer-graphics-ray-casting/shared/cmake/../json/json.hpp:129:14: error: #error "unsupported GCC version - see https://github.com/nlohmann/json#supported-compilers"                                        
In file included from /u/c/sissonde/computer-graphics-ray-casting/include/read_json.h:24,                     
                 from /u/c/sissonde/computer-graphics-ray-casting/main.cpp:6:                                 
/u/c/sissonde/computer-graphics-ray-casting/shared/cmake/../json/json.hpp:110: error: expected nested-name-specifier before ‘json’                                                                                          
/u/c/sissonde/computer-graphics-ray-casting/shared/cmake/../json/json.hpp:110: error: ‘json’ has not been declared                                                                                                          
/u/c/sissonde/computer-graphics-ray-casting/shared/cmake/../json/json.hpp:110: error: expected ‘;’ before ‘=’ token                                                                                                         
/u/c/sissonde/computer-graphics-ray-casting/shared/cmake/../json/json.hpp:110: error: expected unqualified-id before ‘=’ token                                                                                              
In file included from /u/c/sissonde/computer-graphics-ray-casting/include/read_json.h:24,                     
                 from /u/c/sissonde/computer-graphics-ray-casting/main.cpp:6:                                 
/u/c/sissonde/computer-graphics-ray-casting/shared/cmake/../json/json.hpp:271: error: expected unqualified-id before ‘using’                                                                                                
/u/c/sissonde/computer-graphics-ray-casting/shared/cmake/../json/json.hpp:274: error: expected unqualified-id before ‘using’                                                                                                
/u/c/sissonde/computer-graphics-ray-casting/shared/cmake/../json/json.hpp:281: error: expected nested-name-specifier before ‘type’                                                                                          
/u/c/sissonde/computer-graphics-ray-casting/shared/cmake/../json/json.hpp:281: error: using-declaration for non-member at class scope                                                                                       
/u/c/sissonde/computer-graphics-ray-casting/shared/cmake/../json/json.hpp:281: error: expected ‘;’ before ‘=’ token                                                                                                         
/u/c/sissonde/computer-graphics-ray-casting/shared/cmake/../json/json.hpp:281: error: expected unqualified-id before ‘=’ token                                                                                              
/u/c/sissonde/computer-graphics-ray-casting/shared/cmake/../json/json.hpp:282: error: expected nested-name-specifier before ‘value_type’                                                                                    
/u/c/sissonde/computer-graphics-ray-casting/shared/cmake/../json/json.hpp:282: error: using-declaration for non-member at class scope                                                                                       
/u/c/sissonde/computer-graphics-ray-casting/shared/cmake/../json/json.hpp:282: error: expected ‘;’ before ‘=’ token                                                                                                         
/u/c/sissonde/computer-graphics-ray-casting/shared/cmake/../json/json.hpp:282: error: expected unqualified-id before ‘=’ token                                                                                              
/u/c/sissonde/computer-graphics-ray-casting/shared/cmake/../json/json.hpp:283: error: ‘constexpr’ does not name a type                                                                                                      
/u/c/sissonde/computer-graphics-ray-casting/shared/cmake/../json/json.hpp:305: error: expected unqualified-id before ‘using’                                                                                                
/u/c/sissonde/computer-graphics-ray-casting/shared/cmake/../json/json.hpp:343: error: expected ‘;’ before ‘bool’                                                                                                            
/u/c/sissonde/computer-graphics-ray-casting/shared/cmake/../json/json.hpp:344: error: expected ‘;’ before ‘bool’                                                                                                            
/u/c/sissonde/computer-graphics-ray-casting/shared/cmake/../json/json.hpp:345: error: expected ‘;’ before ‘bool’                                                                                                            
/u/c/sissonde/computer-graphics-ray-casting/shared/cmake/../json/json.hpp:346: error: expected ‘;’ before ‘bool’                                                                                                            
/u/c/sissonde/computer-graphics-ray-casting/shared/cmake/../json/json.hpp:354: error: expected ‘;’ before ‘auto’                                                                                                            
/u/c/sissonde/computer-graphics-ray-casting/shared/cmake/../json/json.hpp:365: error: expected ‘;’ before ‘auto’                                                                                                            
/u/c/sissonde/computer-graphics-ray-casting/shared/cmake/../json/json.hpp:373: error: declaration of ‘auto nlohmann::detail::is_compatible_object_type<BasicJsonType, CompatibleObjectType>::constexpr’ has no initializer  
/u/c/sissonde/computer-graphics-ray-casting/shared/cmake/../json/json.hpp:373: error: expected ‘;’ before ‘value’                                                                                                           
/u/c/sissonde/computer-graphics-ray-casting/shared/cmake/../json/json.hpp:383: error: declaration of ‘auto nlohmann::detail::is_compatible_string_type<BasicJsonType, CompatibleStringType>::constexpr’ has no initializer  
/u/c/sissonde/computer-graphics-ray-casting/shared/cmake/../json/json.hpp:383: error: expected ‘;’ before ‘value’                                                                                                           
/u/c/sissonde/computer-graphics-ray-casting/shared/cmake/../json/json.hpp:392: error: declaration of ‘auto nlohmann::detail::is_basic_json_nested_type<BasicJsonType, T>::constexpr’ has no initializer                     
/u/c/sissonde/computer-graphics-ray-casting/shared/cmake/../json/json.hpp:392: error: expected ‘;’ before ‘value’                                                                                                           
/u/c/sissonde/computer-graphics-ray-casting/shared/cmake/../json/json.hpp:401: error: declaration of ‘auto nlohmann::detail::is_compatible_array_type<BasicJsonType, CompatibleArrayType>::constexpr’ has no initializer    
/u/c/sissonde/computer-graphics-ray-casting/shared/cmake/../json/json.hpp:401: error: expected ‘;’ before ‘value’                                                                                                           
/u/c/sissonde/computer-graphics-ray-casting/shared/cmake/../json/json.hpp:419: error: expected nested-name-specifier before ‘RealLimits’                                                                                    
/u/c/sissonde/computer-graphics-ray-casting/shared/cmake/../json/json.hpp:419: error: using-declaration for non-member at class scope                                                                                       
/u/c/sissonde/computer-graphics-ray-casting/shared/cmake/../json/json.hpp:419: error: expected ‘;’ before ‘=’ token                                                                                                         
/u/c/sissonde/computer-graphics-ray-casting/shared/cmake/../json/json.hpp:419: error: expected unqualified-id before ‘=’ token                                                                                              
/u/c/sissonde/computer-graphics-ray-casting/shared/cmake/../json/json.hpp:420: error: expected nested-name-specifier before ‘CompatibleLimits’                                                                              
/u/c/sissonde/computer-graphics-ray-casting/shared/cmake/../json/json.hpp:420: error: using-declaration for non-member at class scope                                                                                       
/u/c/sissonde/computer-graphics-ray-casting/shared/cmake/../json/json.hpp:420: error: expected ‘;’ before ‘=’ token                                                                                                         
/u/c/sissonde/computer-graphics-ray-casting/shared/cmake/../json/json.hpp:420: error: expected unqualified-id before ‘=’ token                                                                                              
/u/c/sissonde/computer-graphics-ray-casting/shared/cmake/../json/json.hpp:422: error: expected ‘;’ before ‘auto’                                                                                                            
/u/c/sissonde/computer-graphics-ray-casting/shared/cmake/../json/json.hpp:431: error: expected ‘;’ before ‘auto’                                                                                                            
/u/c/sissonde/computer-graphics-ray-casting/shared/cmake/../json/json.hpp:444: error: expected type-specifier before ‘enable_if_t’                                                                                          
/u/c/sissonde/computer-graphics-ray-casting/shared/cmake/../json/json.hpp:444: error: expected ‘>’ before ‘enable_if_t’                                                                                                     
/u/c/sissonde/computer-graphics-ray-casting/shared/cmake/../json/json.hpp:450: error: expected ‘;’ before ‘bool’                                                                                                            
/u/c/sissonde/computer-graphics-ray-casting/shared/cmake/../json/json.hpp:462: error: expected type-specifier before ‘enable_if_t’                                                                                          
/u/c/sissonde/computer-graphics-ray-casting/shared/cmake/../json/json.hpp:462: error: expected ‘>’ before ‘enable_if_t’                                                                                                     
/u/c/sissonde/computer-graphics-ray-casting/shared/cmake/../json/json.hpp:468: error: expected ‘;’ before ‘bool’                                                                                                            
/u/c/sissonde/computer-graphics-ray-casting/shared/cmake/../json/json.hpp:477: error: ‘uncvref_t’ was not declared in this scope                                                                                            
/u/c/sissonde/computer-graphics-ray-casting/shared/cmake/../json/json.hpp:477: error: ‘uncvref_t’ was not declared in this scope                                                                                            
/u/c/sissonde/computer-graphics-ray-casting/shared/cmake/../json/json.hpp:477: error: expected primary-expression before ‘>’ token                                                                                          
/u/c/sissonde/computer-graphics-ray-casting/shared/cmake/../json/json.hpp:477: error: ‘::to_json’ has not been declared                                                                                                     
/u/c/sissonde/computer-graphics-ray-casting/shared/cmake/../json/json.hpp:478: error: ‘declval’ is not a member of ‘std’                                                                                                    
/u/c/sissonde/computer-graphics-ray-casting/shared/cmake/../json/json.hpp:478: error: expected primary-expression before ‘&’ token                                                                                          
/u/c/sissonde/computer-graphics-ray-casting/shared/cmake/../json/json.hpp:478: error: expected primary-expression before ‘>’ token                                                                                          
/u/c/sissonde/computer-graphics-ray-casting/shared/cmake/../json/json.hpp:478: error: expected primary-expression before ‘)’ token                                                                                          
/u/c/sissonde/computer-graphics-ray-casting/shared/cmake/../json/json.hpp:478: error: ‘declval’ is not a member of ‘std’                                                                                                    
/u/c/sissonde/computer-graphics-ray-casting/shared/cmake/../json/json.hpp:478: error: expected primary-expression before ‘>’ token                                                                                          
/u/c/sissonde/computer-graphics-ray-casting/shared/cmake/../json/json.hpp:478: error: expected primary-expression before ‘)’ token                                                                                          
/u/c/sissonde/computer-graphics-ray-casting/shared/cmake/../json/json.hpp:483: error: expected ‘;’ before ‘bool’                                                                                                            
/u/c/sissonde/computer-graphics-ray-casting/shared/cmake/../json/json.hpp:490: error: expected ‘;’ before ‘bool’                                                                                                            
/u/c/sissonde/computer-graphics-ray-casting/shared/cmake/../json/json.hpp:508: error: ‘constexpr’ does not name a type                                                                                                      
/u/c/sissonde/computer-graphics-ray-casting/shared/cmake/../json/json.hpp:512: error: expected constructor, destructor, or type conversion before ‘T’                                                                       
In file included from /u/c/sissonde/computer-graphics-ray-casting/include/read_json.h:24,                     
                 from /u/c/sissonde/computer-graphics-ray-casting/main.cpp:6:                                 
/u/c/sissonde/computer-graphics-ray-casting/shared/cmake/../json/json.hpp:563: error: expected ‘;’ before ‘noexcept’                                                                                                        
/u/c/sissonde/computer-graphics-ray-casting/shared/cmake/../json/json.hpp:569: error: expected ‘;’ before ‘const’                                                                                                           
/u/c/sissonde/computer-graphics-ray-casting/shared/cmake/../json/json.hpp: In static member function ‘static std::string nlohmann::detail::exception::name(const std::string&, int)’:                                       
/u/c/sissonde/computer-graphics-ray-casting/shared/cmake/../json/json.hpp:576: error: call of overloaded ‘to_string(int&)’ is ambiguous                                                                                     
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2604: note: candidates are: std::string std::to_string(long long int)                                                              
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2610: note:                 std::string std::to_string(long long unsigned int)                                                     
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2616: note:                 std::string std::to_string(long double)                                                                
In file included from /u/c/sissonde/computer-graphics-ray-casting/include/read_json.h:24,                     
                 from /u/c/sissonde/computer-graphics-ray-casting/main.cpp:6:                                 
/u/c/sissonde/computer-graphics-ray-casting/shared/cmake/../json/json.hpp: In static member function ‘static nlohmann::detail::parse_error nlohmann::detail::parse_error::create(int, size_t, const std::string&)’:         
/u/c/sissonde/computer-graphics-ray-casting/shared/cmake/../json/json.hpp:641: error: call of overloaded ‘to_string(size_t&)’ is ambiguous                                                                                  
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2604: note: candidates are: std::string std::to_string(long long int)                                                              
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2610: note:                 std::string std::to_string(long long unsigned int)                                                     
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2616: note:                 std::string std::to_string(long double)                                                                
In file included from /u/c/sissonde/computer-graphics-ray-casting/include/read_json.h:24,                     
                 from /u/c/sissonde/computer-graphics-ray-casting/main.cpp:6:                                 
/u/c/sissonde/computer-graphics-ray-casting/shared/cmake/../json/json.hpp: At global scope:                   
/u/c/sissonde/computer-graphics-ray-casting/shared/cmake/../json/json.hpp:911: error: expected initializer before ‘noexcept’                                                                                                
In file included from /u/c/sissonde/computer-graphics-ray-casting/include/read_json.h:24,                     
                 from /u/c/sissonde/computer-graphics-ray-casting/main.cpp:6:                                 
/u/c/sissonde/computer-graphics-ray-casting/shared/cmake/../json/json.hpp:18570: error: expected ‘}’ before end of line                                                                                                     
/u/c/sissonde/computer-graphics-ray-casting/shared/cmake/../json/json.hpp:18570: error: expected ‘}’ before end of line                                                                                                     
/u/c/sissonde/computer-graphics-ray-casting/shared/cmake/../json/json.hpp:18570: error: expected declaration before end of line                                                                                             
make[2]: *** [CMakeFiles/raycasting.dir/main.cpp.o] Error 1                                                   
make[1]: *** [CMakeFiles/raycasting.dir/all] Error 2                                                          
make: *** [all] Error 2 

As expected, the error is coming from main.cpp's include statement to read_json.cpp's line which includes "json.hpp" in the json folder. No changes have been made to the program.

I'm not sure how to proceed, does anyone have ideas?

**Comment by alecjacobson** [comment]
To fix this ECF needs to update to a non-buggy GCC version.
