### ISSUE TITLE
confusion on focal length and eye position

### ISSUE THREAD

**Issue by nafis95** [alecjacobson/computer-graphics-ray-casting#2]
When i was writing code for viewing_ray, i noticed that in the .json files, the eye and the focal length have different values. Example, for the sphere_and_plane.json file,

"focal_length": 3, 
"eye": [0,0,5],

So I am bit confused here as based on lecture, I though the eye would be positioned at the focal point.

Another point, in the readme, its mentioned -

_The image rectangle (e.g., 640 pixels by 360 pixels) is placed so the image center is directly in front of the "eye" point at a certain "focal length" $d$._

However, in some of the .json files, i dont think it follows this assumption. For example, in the sphere-packing.json file,

"eye": [9.6,0.3,10],

So is the eye positioned such that it is looking at the image screen at an angle? Or is the image plane also rotated to match the eye?

**Comment by velociraptor111** [comment]
The way I see it is that, when the eye is at location "eye": [0,0,5]" and the "focal_length": 3
this means that the image plane is at position [0,0,2]
