### ISSUE TITLE
How to run the release build

### ISSUE THREAD

**Issue by QiiLin** [alecjacobson/computer-graphics-ray-casting#25]
I did the following 
``` 
mkdir build-release
cd build-release
cmake ../ -DCMAKE_BUILD_TYPE=Release
make
```
but make gives the following outcome:
make: *** No targets specified and no makefile found.  Stop.
I am on windows and install the make using
```
choco install make
```
right now is an issue is that the bunny takes forever to run... I know by using build release, I can do this much faster... but the make on windows doesn't seem to be working...? For assignment 1, I just open the sln file in visual studio and build the solution, this will generate a folder called Debug in build_release folder.  And I will cd to that Debug folder and execute the exe from there.  I tried the same thing for assignment 2... but the running time of bunny is just way too long. ... any suggestion or advice on running this on windows?

**Comment by psarahdactyl** [comment]
Once you've run cmake with the CMAKE_BUILD_TYPE parameter set to Release, you can open the sln file in Visual Studio. In Visual Studio there is a dropdown menu that says Debug on it. Select Release and build it from there
https://docs.microsoft.com/en-us/visualstudio/debugger/how-to-set-debug-and-release-configurations?view=vs-2019

**Comment by QiiLin** [comment]
Thanks.
