### ISSUE TITLE
Error on read_json.h

### ISSUE THREAD

**Issue by vinaykomaravolu** [alecjacobson/computer-graphics-ray-casting#3]
**I get this error from read_json,h when I run make in linux. I have not changed/edited/added any code! Is there a way to fix this?**

computer-graphics-ray-casting/include/read_json.h:94:22: error: converting to ‘std::tuple<Eigen::Matrix<double, 3,
1, 0, 3, 1>, Eigen::Matrix<double, 3, 1, 0, 3, 1>, Eigen::Matrix<double, 3, 1, 0, 3, 1> >’ from initializer list would use explicit constructor ‘constexpr std::tuple< <template-parameter-1-1> >::tuple(_UElements&& ...) [with _UElements = {Eigen::Matrix<double, 3, 1, 0, 3, 1>, Eigen::Matrix<double, 3, 1, 0, 3, 1>, Eigen::Matrix<double, 3, 1, 0, 3, 1>};
<template-parameter-2-2> = void; _Elements = {Eigen::Matrix<double, 3, 1, 0, 3, 1>, Eigen::Matrix<double, 3, 1, 0, 3, 1>, Eigen::Matrix<double, 3, 1, 0, 3, 1>}]’
         tri->corners = {
                      ^
computer-graphics-ray-casting/include/read_json.h:121:24: error: converting to ‘std::tuple<Eigen::Matrix<double, 3, 1, 0, 3, 1>, Eigen::Matrix<double, 3, 1, 0, 3, 1>, Eigen::Matrix<double, 3, 1, 0, 3, 1> >’ from initializer list would use explicit constructor ‘constexpr std::tuple< <template-parameter-1-1> >::tuple(_UElements&& ...) [with _UElements = {Eigen::Matrix<double, 3, 1, 0, 3, 1>, Eigen::Matrix<double, 3, 1, 0, 3, 1>, Eigen::Matrix<double, 3, 1, 0, 3, 1>}; <template-parameter-2-2> = void; _Elements = {Eigen::Matrix<double, 3, 1, 0, 3, 1>, Eigen::Matrix<double, 3, 1, 0, 3, 1>, Eigen::Matrix<double, 3, 1, 0, 3, 1>}]’
           tri->corners = {

**Comment by alecjacobson** [comment]
what compiler are you using?

**Comment by vinaykomaravolu** [comment]
This is what I get during "cmake ..".

-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test COMPILER_SUPPORTS_CXX11
-- Performing Test COMPILER_SUPPORTS_CXX11 - Success
-- Performing Test COMPILER_SUPPORTS_CXX0X
-- Performing Test COMPILER_SUPPORTS_CXX0X - Success

**Comment by alecjacobson** [comment]
thank you. I can reproduce this. Will push a fix shortly.

**Comment by vinaykomaravolu** [comment]
Thank you!

**Comment by alecjacobson** [comment]
Fixed in 71cf44378e3f081b5534c75a0ae089fa9cb2c080
